version: 2
updates:
  # Python bağımlılıkları
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub Actions (CI/CD varsa)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"